name: Call reusable workflows

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - main
      - devel
    types:
      - closed
    paths:
      - '.github/workflows/reuse-build-and-publish-amd.yml'
      - '.devcontainer/devcontainer.json'
      - 'Dockerfile'
      - 'reinstall-cmake.sh'
      - 'VERSION'

jobs:
  call-workflow-amd64:
    permissions:
      contents: read
      packages: write
    uses: iaine/r-dev-env/.github/workflows/reuse-build-and-publish.yml@${{ github.ref_name }}
    with:
      image_name: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      registry: ghcr.io
    secrets: inherit
