name: Call reusable workflows

on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - main
      - devel
    types:
      - closed
    paths:
      - '.github/workflows/reuse-build-and-publish-amd.yml'
      - '.devcontainer/devcontainer.json'
      - 'Dockerfile'
      - 'reinstall-cmake.sh'
      - 'VERSION'

jobs:
  call-workflow-amd64-main:
    if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reuse-build-and-publish.yml
    with:
      image_name: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      registry: ghcr.io
    secrets: inherit
  call-workflow-amd64-devel:
    if: ${{ github.ref_name == 'devel' }}
    uses: iaine/r-dev-env/.github/workflows/reuse-build-and-publish.yml@devel
    with:
      image_name: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      registry: ghcr.io
    secrets: inherit
