name: Call reusable workflows

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel
    types:
      - closed
    paths:
      - '.github/workflows/reuse-build-and-publish-amd.yml'
      - '.devcontainer/devcontainer.json'
      - 'Dockerfile'
      - 'reinstall-cmake.sh'
      - 'VERSION'

jobs:
  call-workflow-amd64:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reuse-build-and-publish.yml
    with:
      image_name: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      registry: ghcr.io
      platform: amd
    secrets: inherit
  call-workflow-arm64:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reuse-build-and-publish-arm.yml
    with:
      image_name: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      actor: ${{ github.actor }}
      registry: ghcr.io
      platform: arm
    secrets: inherit
  #call-workflow-both:
  #  permissions:
  #    contents: read
  #    packages: write
  ##  uses: ./.github/workflows/reuse-build-and-publish-buildx.yml
  #  with:
  #    image_name: ${{ github.repository }}
  #    ref_name: ${{ github.ref_name }}
  #    actor: ${{ github.actor }}
  #    registry: ghcr.io
  #    platform: buildx
  #  secrets: inherit
  call-workflow-manifest:
    needs:
      - call-workflow-amd64
      - call-workflow-arm64
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/reuse-build-manifest.yml
    with:
      image_name: ${{ github.repository }}
      ref_name: ${{ github.ref_name }}
      registry: ghcr.io
    secrets: inherit
