# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build and publish arm64 && amd 64 Docker image using buildx

on:
  workflow_call:
    inputs:
      image_name:
        description: image name
        required: true
        type: string
      ref_name:
        description: ref name
        required: true
        type: string
      actor:
        description: actor
        required: true
        type: string
      registry:
        description: registry
        required: true
        type: string
      platform:
        description: platform
        required: true
        type: string
permissions:
  contents: read
  packages: write

jobs:
  reuse-build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version number
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=${{ env.VERSION }}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          pull: true
          tags: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ inputs.ref_name }}-${{ inputs.platform }}
          build-args: |
            CONTAINER_VERSION=${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64/v8
      - name: Write manifest and build history file
        run: |
          sudo apt-get install r-base -y && sudo Rscript -e "install.packages('optparse')" \
            && Rscript scripts/manifest.R \
            --registry ${{ inputs.registry }} \
            --owner ${{ inputs.actor}} \
            --image ${{ inputs.ref_name }} \
            --historydir /tmp/r-devel/hist_lines \
            --manifestdir /tmp/r-devel/manifests \
            --repository ${{ inputs.image_name }}
        shell: bash
      - name: Upload manifest file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.platform }}-manifest
          path: /tmp/r-devel/manifests/manifest-*.md
          retention-days: 3
      - name: Upload build history line
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.platform }}-history_line
          path: /tmp/r-devel/hist_lines/history-*.txt
          retention-days: 3
